// vue-client/src/router/components/Info.vue
<template functional>
  <div id="info">
    <h1>INFO</h1>
    <h4>
      This application is built as part of my full-stack JavaScript portfolio.
      <br />
      You can find the exact same front end built in React and Materialize from
      <a href="http://localhost:3000/table" target="_blank"> here</a>.
    </h4>
    <br />
    <h4>
      <a
        href="https://github.com/elarsaks/JavaScript-Portfolio"
        target="_blank"
      >
        Link to project GitHub
      </a>
    </h4>
  </div>
</template>

<style scoped>
#info {
  text-align: center;
  font-weight: 200;
  font-size: 150%;
}
</style>

// react-client/src/features/info/Info.tsx
export default function Info() {
    return (
        <div style={{ textAlign: "center" }}>
            <h1>INFO</h1>
            <h4>
                This application is a built as part of my full-stack JavaScript
                portfolio.
                <br></br>
                You can find the exact same front end built in vue and Vuetify
                from{" "}
                <a href='http://localhost:8080/table' target='_blank'>
                    here
                </a>
                .
            </h4>
            <br></br>
            <br></br>
            <h4>
                <a href='https://github.com/elarsaks/solita' target='_blank'>
                    Link to project GitHub
                </a>
            </h4>
        </div>
    )
}
