// client/src/router/components/Table.vue
<template>
  <v-simple-table fixed-header height="80vh" width="50vw">
    <template v-slot:default>
      <thead>
        <tr>
          <th class="text-left">
            Name
          </th>
          <th class="text-left">
            Amount
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in names" :key="item.name">
          <td>{{ item.name }}</td>
          <td>{{ item.amount }}</td>
        </tr>
      </tbody>
    </template>
  </v-simple-table>
</template>

<script>
export default {
  name: 'Table',
  props: {
    names: {
      type: Array,
      required: true,
      default() {
        return []
      },
    },
  },
}
</script>

<style scoped></style>

// react-client/src/router/components/Table.js
import React, { useState } from 'react'
import { Table as DataTable } from 'react-materialize'
import SortButton from './helpers/SortButton'

const style = {
  dataTable: {
    width: '90vw',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
}

export default function Table(props) {
  const [state, setState] = useState({
    selectedColumn: 'names',
    sortOrder: {
      names: true,
      amount: false,
    },
  })

  function sortTable(column) {
    setState({
      ...state,
      selectedColumn: column,
      sortOrder: {
        ...state.sortOrder,
        [column]: !state.sortOrder[column],
      },
    })

    // Call here function actually sorting a table
  }

  return (
    <DataTable style={style.dataTable} className='centered'>
      <thead>
        <tr>
          <th>
            <SortButton
              text='names'
              state={state}
              sortTable={() => sortTable('names')}
            />
          </th>
          <th>
            <SortButton
              text='amount'
              state={state}
              sortTable={() => sortTable('amount')}
            />
          </th>
        </tr>
      </thead>
      <tbody>
        {props.names.map((item) => (
          <tr key={item.name}>
            <td>{item.name}</td>
            <td>{item.amount}</td>
          </tr>
        ))}
      </tbody>
    </DataTable>
  )
}
