// react-client/src/pages/table/Table.js
import React, { useState } from 'react'
import { Table as DataTable } from 'react-materialize'
import SortButton from './components/SortButton'

const style = {
  dataTable: {
    width: '90vw',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
}

export default function Table(props) {
  const [sorting, setSorting] = useState({
    selectedColumn: 'names',
    sortOrder: {
      names: true,
      amount: false,
    },
  })

  function sortTable(column) {
    setSorting({
      ...sorting,
      selectedColumn: column,
      sortOrder: {
        ...sorting.sortOrder,
        [column]: !sorting.sortOrder[column],
      },
    })

    // Call here function actually sorting a table
  }

  return (
    <DataTable style={style.dataTable} className='centered'>
      <thead>
        <tr>
          <th>
            <SortButton
              text='names'
              sorting={sorting}
              sortTable={() => sortTable('names')}
            />
          </th>
          <th>
            <SortButton
              text='amount'
              sorting={sorting}
              sortTable={() => sortTable('amount')}
            />
          </th>
        </tr>
      </thead>
      <tbody>
        {props.names.map((item) => (
          <tr key={item.name}>
            <td>{item.name}</td>
            <td>{item.amount}</td>
          </tr>
        ))}
      </tbody>
    </DataTable>
  )
}

// client/src/router/components/Table.vue
<template>
  <v-simple-table fixed-header height="80vh" width="50vw">
    <template v-slot:default>
      <thead>
        <tr>
          <th class="text-left">
            Names (Count - {{ names.length }})
            <SortIcon
              column="names"
              :selectedColumn="selectedColumn"
              :sort="sort.names"
              @sortBy="setSortBy"
            />
          </th>

          <th class="text-left">
            Amount (Total - ??)
            <SortIcon
              column="amount"
              :selectedColumn="selectedColumn"
              :sort="sort.amount"
              @sortBy="setSortBy"
            />
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in names" :key="item.name">
          <td>{{ item.name }}</td>
          <td>{{ item.amount }}</td>
        </tr>
      </tbody>
    </template>
  </v-simple-table>
</template>

<script>
import SortIcon from '../../components/SortIcon.vue'

export default {
  name: 'Table',
  props: {
    names: {
      type: Array,
      required: true,
      default() {
        return []
      },
    },
  },
  components: {
    SortIcon,
  },
  data() {
    return {
      selectedColumn: 'names',
      sort: {
        names: true,
        amount: false,
      },
    }
  },
  methods: {
    setSortBy(column) {
      if (this.selectedColumn == column) {
        this.sort[column] = !this.sort[column]
      } else {
        this.selectedColumn = column
        this.sort[column] = !this.sort[column]
      }
    },
  },
}
</script>

<style scoped></style>
